Repository mojohaus/xml-maven-plugin, pull requests merged in 2023-11, with the labels that each got.

#100 Downgrade plexus-xml to 3.0.0
  pom.xml
Labels: dependencies

#101 Require Maven 3.6.3+
  pom.xml
Labels: enhancement, dependencies

#102 Use default Maven version for build
  .github/workflows/maven.yml
Labels: build
